"""
Django settings for unisat project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

UNISAT_DOMAIN = os.environ.get("UNISAT_DOMAIN", "https://xlnk.azat.ai")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-omx1!_7$x+)$hxv#8(dy!218qzez8j%1&_p-_w%x8me%l82_=#')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', '') != 'False'

ALLOWED_HOSTS = ['azt.local',
                 'xlink.kz',
                 'localhost',
                 '0.0.0.0',
                 '127.0.0.1',
                 '*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'adapter',
    "drf_yasg",
    'corsheaders',
    "django.contrib.sites",
    "rest_framework",
    'rest_framework.authtoken',
    "storages",
    'user_agents',
    'phonenumbers',
    'phonenumber_field',
    'transliterate',
    "oauth2_provider",
    "azt_connect.apps.AztConnectConfig",

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    # AzatAI/@azaza7087
    # Added a middleware for user-agent
    'django_user_agents.middleware.UserAgentMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'unigate.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'unigate.wsgi.application'
PHONENUMBER_DB_FORMAT = 'NATIONAL'
PHONENUMBER_DEFAULT_REGION = 'KZ'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
#

# AzatAI/@azaza7087
# Added a configurations for drf_yasg
SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': False,

    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:6006",
    "http://localhost:6005",
    "http://127.0.0.1:6005",
    "http://127.0.0.1:6006",
    "http://10.22.22.33:6005",
    "http://10.22.22.33:6006",
    'http://azt.local',
    'http://xlink.kz',
    'http://localhost',
    'http://0.0.0.0',
    'http://127.0.0.1'
]

CORS_ALLOW_CREDENTIALS = True

AUTH_USER_MODEL = 'adapter.User'


AZT_CONNECT = {
    'PROJECT_NAME': 'unigate',
    'AZT_DB': {
        'ENABLE': False,  # default False
        'MODE': 'DEVELOPMENT',  # default DEVELOPMENT
        'DB_NAME': 'unigate',  # MANDATORY, default None
    },
    'AZT_S3': {
        'ENABLE': True,  # default False
    },
    'SITE_ID': 1,  # default 1
    'AZT_EMAIL_BACKEND': {
        'ENABLE': True,  # default False
        'EMAIL_HOST': "smtp-relay.gmail.com",
        'DEFAULT_FROM_EMAIL': "info@azat.ai"
    },
    'AZT_AUTH': {
        'ENABLE': True,
        'AUTH_URL': 'https://auth.azt.one/',
        "CLIENT_ID": 'AkI2kJ8B54h80MtTJVvzqfAw3sVDefPWGFb4ZZvJ',
        "CLIENT_SECRET": '8nZbdyvnO0PZY3r7hnus9oA5DC6PzmEJP5D2C7xpGyhyZUBygTEugaZ0C5Hv8ud4w4K7zKhLoX71P2Whl3sQP4nkU2SA7bji63DYeEjFoqnQqfsz0KDm5h4KFNXv0Wn0'

    }
}
from azt_connect.settings_reload import *

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'unigate',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

REST_FRAMEWORK['DEFAULT_PAGINATION_CLASS'] = 'rest_framework.pagination.PageNumberPagination'
REST_FRAMEWORK['PAGE_SIZE'] = 5
